version: '3'
services:
  backend:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      backend-network:
        ipv4_address: 192.168.0.13

networks:
  backend-network:
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  todo-mysql-data:
